// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders:          number;
    paidOrders:              number;
    numberOfClients:         number;
    numberOfProducts:        number;
    productsWithNoInventory: number;
    lowInventory:            number;
    notPaidOrders:           number;
}


/*
export interface DashboardSummaryResponse {
    numberOfTickets:         number;
    unsolvedTickets:         number;
    equipments     :         number;
    :        number;
    lowInventory:            number;

}
*/